@startuml
package edu.unl.webautomator.core {
    'package edu.unl.webautomator.core.internal {}

    package edu.unl.webautomator.core.model {
     'package edu.unl.webautomator.core.model.internal {}

    }
    package edu.unl.webautomator.core.configuration {
        'package edu.unl.webautomator.core.configuration.internal{}
    }
    package edu.unl.webautomator.core.platform {
        'package edu.unl.webautomator.core.platform.internal{}
    }
    package edu.unl.webautomator.core.converter{
        'package edu.unl.webautomator.core.converter.internal{}
    }
    package edu.unl.webautomator.core.executor{
        'package edu.unl.webautomator.core.executor.internal{}
    }
    package edu.unl.webautomator.core.extractor{
        'package edu.unl.webautomator.core.extractor.internal{}
    }
    package edu.unl.webautomator.core.provider{
        'package edu.unl.webautomator.core.provider.internal{}
    }
}




interface edu.unl.webautomator.core.model.Event
interface edu.unl.webautomator.core.model.WebEvent
interface edu.unl.webautomator.core.model.TestCase
interface edu.unl.webautomator.core.model.TestCaseExecutionResult
interface edu.unl.webautomator.core.model.State

class edu.unl.webautomator.core.configuration.WebAutomatorConfiguration
class edu.unl.webautomator.core.configuration.WebBrowserConfiguration
class edu.unl.webautomator.core.configuration.WebProxyConfiguration
class edu.unl.webautomator.core.configuration.EventTypeConfiguration

class edu.unl.webautomator.core.Automator
interface edu.unl.webautomator.core.WebAutomator
class edu.unl.webautomator.core.WebAutomatorBase
enum edu.unl.webautomator.core.BrowserType
interface edu.unl.webautomator.core.converter.TestCaseConverter
interface edu.unl.webautomator.core.executor.EventExecutor
interface edu.unl.webautomator.core.extractor.StateExtractor
interface edu.unl.webautomator.core.extractor.EventExtractor
interface edu.unl.webautomator.core.provider.EventInputProvider






enum edu.unl.webautomator.core.BrowserType{
    CHROME
    FIREFOX
    IEXPLORER
    PHANTOMJS
    REMOTE
}


@enduml

/*
abstract class AbstractList
abstract AbstractCollection
interface List
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractList <|-- ArrayList

class ArrayList {
+ Object[] elementData
- size()
}

enum TimeUnit {
  DAYS
  HOURS
  MINUTES
}
*/